ColoursOfDance/Models/CourseViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ColoursOfDance.Models
{
    public class CourseViewModel
    {
        public IEnumerable<Courses> Courses { get; set; }
        public IEnumerable<Students> Students { get; set; }
    }
}

ColoursOfDance/Models/Courses.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColoursOfDance.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Courses
    {
        public Courses()
        {
            this.Students = new HashSet<Students>();
        }
        [Display(Name = "Id curs")]
        public int IdCourse { get; set; }
        [Display(Name="Denumire curs")]
        public string Name { get; set; }
        [DataType(DataType.MultilineText)]
        [Display(Name = "Descriere curs")]
        public string Description { get; set; }
        [Display(Name = "Imagine")]
        public byte[] Image { get; set; }
        public int IdCategory { get; set; }
        [Display(Name = "Ziua saptamanii")]
        public string DayOfWeek { get; set; }
        [Display(Name = "Sala")]
        public string Room { get; set; }
        [Display(Name = "Ora")]
        public Nullable<System.TimeSpan> Hour { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual ICollection<Students> Students { get; set; }
    }
}

ColoursOfDance/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ColoursOfDance.Models;

namespace ColoursOfDance.Controllers
{
    [Authorize]
    public class CourseController : Controller
    {
        private ColoursOfDanceEntities1 db = new ColoursOfDanceEntities1();

        //
        // GET: /Admin/
        public ActionResult Index(int? id)
        {
            var courseView = new CourseViewModel();
            courseView.Courses = db.Courses
                .Include(c => c.Categories)
                .Include(c => c.Students)
                .OrderBy(c => c.Name);
            if (id != null)
            {
                ViewBag.CourseId = id.Value;
                courseView.Students = courseView.Courses.Where(
                    c => c.IdCourse == id.Value).Single().Students;
            }
            return View(courseView);
        }

        public JsonResult GetStudentsEnrolled()
        {
            List<Courses> Courses = db.Courses.ToList();
            List<DataChart> data = new List<DataChart>();
            foreach(var course in Courses)
            {
                int nr = course.Students.Count;
                DataChart aux = new DataChart()
                {
                    Course = course.Name,
                    NumberOfStudents = nr
                };
                data.Add(aux);
            }
            return Json(data);
        }

        public ActionResult Details(int id = 0)
        {
            Courses courses = db.Courses.Find(id);
            if (courses == null)
            {
                return HttpNotFound();
            }
            return View(courses);
        }

        [Authorize(Users = "Simi")]
        public ActionResult Create()
        {
            ViewBag.IdCategory = new SelectList(db.Categories, "IdCategory", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Users = "Simi")]
        public ActionResult Create(Courses courses, HttpPostedFileBase image2)
        {
            if (image2 != null)
            {
                courses.Image = new byte[image2.ContentLength];
                image2.InputStream.Read(courses.Image, 0, image2.ContentLength);
            }
            if (ModelState.IsValid)
            {
                db.Courses.Add(courses);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdCategory = new SelectList(db.Categories, "IdCategory", "Name", courses.IdCategory);
            return View(courses);
        }


        [Authorize(Users = "Simi")]
        public ActionResult Edit(int id = 0)
        {
            Courses courses = db.Courses.Find(id);
            if (courses == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdCategory = new SelectList(db.Categories, "IdCategory", "Name", courses.IdCategory);
            return View(courses);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Users = "Simi")]
        public ActionResult Edit(Courses courses, HttpPostedFileBase image2)
        {
            if (image2 != null)
            {
                courses.Image = new byte[image2.ContentLength];
                image2.InputStream.Read(courses.Image, 0, image2.ContentLength);
            }
            if (ModelState.IsValid)
            {
                db.Entry(courses).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdCategory = new SelectList(db.Categories, "IdCategory", "Name", courses.IdCategory);
            return View(courses);
        }

        [Authorize(Users = "Simi")]
        public ActionResult Delete(int id = 0)
        {
            Courses courses = db.Courses.Find(id);
            if (courses == null)
            {
                return HttpNotFound();
            }
            return View(courses);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Courses courses = db.Courses.Find(id);
            foreach (var student in courses.Students.ToList())
            {
                courses.Students.Remove(student);
            }
            db.Courses.Remove(courses);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
        public class DataChart
        {
            public String Course { get; set; }
            public int NumberOfStudents { get; set; }
        }
    }
}

ColoursOfDance/Views/Course/Create.cshtml
@model ColoursOfDance.Models.Courses

@{
    ViewBag.Title = "Adaugare curs";
}

<div class="edit_bg">
  
    <h2 style="margin-left:100px;color:white">Adaugare curs</h2>
    <div class="courses_box_section">
        <br />
        @using (Html.BeginForm("Create", "Course", FormMethod.Post, new {enctype="multipart/form-data"}))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            
            <br />
            <div class="editor-label">
                @Html.LabelFor(model => model.Name)
             </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Description)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description)
            </div>
            <div class="editor-label">
                @Html.LabelFor(model => model.DayOfWeek)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.DayOfWeek)
                @Html.ValidationMessageFor(model => model.DayOfWeek)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Hour)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Hour)
                @Html.ValidationMessageFor(model => model.Hour)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Room)
            </div>
             <div class="editor-field">
                @Html.EditorFor(model => model.Room)
                @Html.ValidationMessageFor(model => model.Room)
            </div>

            
             <div class="editor-label">
                @Html.LabelFor(model => model.Categories.Name, new { @class = "editor-label" })
            </div>
            <div class="editor-field">
                @Html.DropDownList("IdCategory", (IEnumerable<SelectListItem>)ViewBag.IdCategory, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdCategory)
            </div>
            
            <div style="margin-top:3px">
                @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "control-label" } })
                <div class="col-md-10">
                    <input type="file" id="image2" name="image2"/>
                </div>
            </div>

        @Html.ActionLink("Inapoi", "Index", "Course", new { @class = "btn btn-primary" })
        <input type="submit" value="Creeaza curs" class="btn btn-success" />
   
        }
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ColoursOfDance/Views/Course/Delete.cshtml
@model ColoursOfDance.Models.Courses

@{
    ViewBag.Title = "Stergere curs";
}

<h2>Stergere curs de dans</h2>

<br /><br />
<h4>Confirmati stergerea acestui curs de dans?</h4>

<fieldset>
    
    <table class="table-bordered">
        <tr>
            <td>
                <div class="display-label">
                    @Html.DisplayNameFor(model => model.IdCourse)
                </div>
            </td>
            <td>
                <div class="display-field">
                    @Html.DisplayFor(model => model.IdCourse)
                </div>
            </td>
        </tr> 
        <tr>

            <td>
                <div class="display-label">
                    @Html.DisplayNameFor(model => model.Name)
                </div>
            </td>
            <td>
                <div class="display-field">
                    @Html.DisplayFor(model => model.Name)
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <div class="display-label">
                    @Html.DisplayNameFor(model => model.Description)
                </div>
            </td>
            <td>
                <div class="display-field">
                    @Html.DisplayFor(model => model.Description)
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <div class="display-label">
                    @Html.DisplayNameFor(model => model.Categories.Name)
                </div>
            </td>
            <td>
                <div class="display-field">
                    @Html.DisplayFor(model => model.Categories.Name)
                </div>
            </td>
        </tr>
    </table>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <br />
        <input type="submit" value="Sterge" class="btn btn-danger"/> 
        @Html.ActionLink("Inapoi", "Index", "Course",new { @class = "btn btn-primary" })
    </p>
}

ColoursOfDance/Views/Course/Details.cshtml
@model ColoursOfDance.Models.Courses

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Courses</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.IdCourse)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.IdCourse)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Description)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Categories.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Categories.Name)
    </div>

</fieldset>
<p>
    @Html.ActionLink("Editeaza", "Edit", "Course", new { id=Model.IdCourse, @class="btn btn-primary" }) |
    @Html.ActionLink("Inapoi", "Index", "Course", new { id = Model.IdCourse })
</p>

ColoursOfDance/Views/Course/Edit.cshtml
@model ColoursOfDance.Models.Courses

@{
    ViewBag.Title = "Editare curs";
}


<div class="edit_bg">
    <h2 style="color: white;margin-left:100px">Editare curs</h2>
    <div class="courses_box_section">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)


            <fieldset>
                <div class="editor-label">
                    <br />
                    @Html.LabelFor(model => model.IdCourse)
                </div>
                <div class="editor-field">
                    @Html.TextBoxFor(model => model.IdCourse, new { @readonly = "readonly" })
                    @Html.ValidationMessageFor(model => model.IdCourse)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.Name)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.Name)
                    @Html.ValidationMessageFor(model => model.Name)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.Description)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.Description)
                    @Html.ValidationMessageFor(model => model.Description)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.IdCategory, "Categorie")
                </div>
                <div class="editor-field">
                    @Html.DropDownList("IdCategory", String.Empty)
                    @Html.ValidationMessageFor(model => model.IdCategory)
                </div>
                <div class="editor-label">
                    @Html.LabelFor(model => model.DayOfWeek)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.DayOfWeek)
                    @Html.ValidationMessageFor(model => model.DayOfWeek)
                </div>
                <div class="editor-label">
                    @Html.LabelFor(model => model.Room)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.Room)
                    @Html.ValidationMessageFor(model => model.Room)
                </div>
                <div class="editor-label">
                    @Html.LabelFor(model => model.Hour)
                </div>

                <div class="editor-field">
                    @Html.EditorFor(model => model.Hour)
                    @Html.ValidationMessageFor(model => model.Hour)
                </div>
                @*
    <div style="margin-top:3px">
        @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "control-label" } })
        <div class="col-md-10">
            <input type="file" id="image2" name="image2" />
        </div>
    </div>
*@
            </fieldset>
            <div>
                <br />
                @Html.ActionLink("Inapoi", "Index", "Course", new { @class = "btn btn-primary" })
                <input type="submit" value="Actualizeaza" class="btn btn-warning" />

            </div>
        }


    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ColoursOfDance/Views/Course/Index.cshtml
@model ColoursOfDance.Models.CourseViewModel

@{
    ViewBag.Title = "Gestiune cursuri";
}

<h2>Gestiune cursuri</h2>
<br />

@Scripts.Render("https://www.gstatic.com/charts/loader.js")
<br />
<table class="table table-bordered" style="margin-top:30px">
    <thead class="thead-inverse" style="background-color:#e7f4f6">
        <tr>
            <th>Denumire curs</th>
            <th>Denumire categorie</th>
            <th>Ziua saptamanii</th>
            <th>Sala</th>
            <th>Ora</th>
            <th>@Html.ActionLink("Adauga curs", "Create", "Course", new { @class = "btn btn-primary" })</th>
        </tr>

    </thead>

    <tbody>
        @foreach (var item in Model.Courses)
        {
            string selectedRow = "";
            if (item.IdCourse == ViewBag.CourseId)
            {
                selectedRow = "active";
            }
            <tr class=@selectedRow>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Categories.Name)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.DayOfWeek)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Room)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Hour)
                </td>

                <td>
                    @Html.ActionLink("Studenti inscrisi", "Index", "Course", new { id = item.IdCourse }, new { @class = "btn btn-primary" })

                    @Html.ActionLink("Editeaza curs", "Edit", "Course", new { id = item.IdCourse }, new { @class = "btn btn-warning" })

                    @Html.ActionLink("Sterge curs", "Delete", "Course", new { id = item.IdCourse }, new { @class = "btn btn-danger" })

                </td>
            </tr>
         }
    </tbody>
</table>

@if (Model.Students != null)
{
    if (Model.Students.Count() == 0)
    {
        <h3 class="text-center alert-danger">Niciun student inscris</h3>
    }
    else
    {
        <h3 class="text-center alert-info">Studenti inscrisi</h3>
        <table class="table table-bordered" style="width:900px">
            <thead class="thead-inverse" style="background-color:#e7f4f6">
                <tr>
                    <th>Nume</th>
                    <th>Varsta</th>
                    <th>Telefon</th>
                    <th>Email</th>
                </tr>
            </thead>

            @foreach (var item in Model.Students)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Age)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Phone)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                </tr>
            }
        </table>
    }
}

<div id="piechart_3d" style="width: 900px; height: 450px; margin-left:140px;"></div>