ColoursOfDance/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ColoursOfDance.Models;

namespace ColoursOfDance.Controllers
{
    public class CategoryController : Controller
    {
        private ColoursOfDanceEntities1 db = new ColoursOfDanceEntities1();

        //
        // GET: /Category/

        public ActionResult Index()
        {
            return View(db.Categories.ToList());
        }

        //
        // GET: /Category/Details/5

        public ActionResult Display(string selectedCourse="19")
        {
            CategoryViewModel viewModel = new CategoryViewModel();
            viewModel.Categories = db.Categories.Include(c => c.Courses).ToList();
            viewModel.Course = db.Courses.Find(Int32.Parse(selectedCourse));
            return View(viewModel);
        }

        public ActionResult Details(int id = 0)
        {
            Categories categories = db.Categories.Find(id);
            if (categories == null)
            {
                return HttpNotFound();
            }
            return View(categories);
        }

        //
        // GET: /Category/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Category/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Categories categories)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(categories);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(categories);
        }

        //
        // GET: /Category/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Categories categories = db.Categories.Find(id);
            if (categories == null)
            {
                return HttpNotFound();
            }
            return View(categories);
        }

        //
        // POST: /Category/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Categories categories)
        {
            
            if (ModelState.IsValid)
            {
                db.Entry(categories).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(categories);
        }

        //
        // GET: /Category/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Categories categories = db.Categories.Find(id);
            if (categories == null)
            {
                return HttpNotFound();
            }
            return View(categories);
        }

        //
        // POST: /Category/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Categories categories = db.Categories.Find(id);
            db.Categories.Remove(categories);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

ColoursOfDance/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ColoursOfDance.Models;


namespace ColoursOfDance.Controllers
{
    [Authorize]
    public class EventController : Controller
    {
        private ColoursOfDanceEntities1 db = new ColoursOfDanceEntities1();

        //
        // GET: /Event/

        public ActionResult Index()
        {
            return View(db.Events.ToList());
        }

        public ActionResult Upcoming()
        {
            return View(db.Events.ToList());
        }

        //
        // GET: /Event/Details/5

        public ActionResult Details(int id = 0)
        {
            Events events = db.Events.Find(id);
            if (events == null)
            {
                return HttpNotFound();
            }
            return View(events);
        }

        //
        // GET: /Event/Create
        
        [Authorize(Users = "Simi")]
        public ActionResult Create()
        {
            Events e=new Events();
            return View(e);
        }
        
        //
        // POST: /Event/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Users = "Simi")]
        public ActionResult Create(Events events, HttpPostedFileBase image1)
        {
            if(image1!=null)
            {
                events.Image = new byte[image1.ContentLength];
                image1.InputStream.Read(events.Image,0,image1.ContentLength);
            }
            if (ModelState.IsValid)
            {
                db.Events.Add(events);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
           
            return View(events);
        }
       


        //
        // GET: /Event/Edit/5
        public ActionResult Edit(int id = 0)
        {
            Events events = db.Events.Find(id);
            if (events == null)
            {
                return HttpNotFound();
            }
            return View(events);
        }

        //
        // POST: /Event/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Events events)
        {
            if (ModelState.IsValid)
            {
                db.Entry(events).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(events);
        }

        //
        // GET: /Event/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Events events = db.Events.Find(id);
            if (events == null)
            {
                return HttpNotFound();
            }
            return View(events);
        }

        //
        // POST: /Event/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Events events = db.Events.Find(id);
            db.Events.Remove(events);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

ColoursOfDance/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ColoursOfDance.Models;

namespace ColoursOfDance.Controllers
{
    public class StudentController : Controller
    {
        private ColoursOfDanceEntities1 db = new ColoursOfDanceEntities1();

        //
        // GET: /Student/

        public ActionResult Index()
        {
            return View(db.Students.ToList());
        }

        //
        // GET: /Student/Details/5

        public ActionResult Details(int id = 0)
        {
            Students students = db.Students.Find(id);
            if (students == null)
            {
                return HttpNotFound();
            }
            return View(students);
        }

        //
        // GET: /Student/Create

        public ActionResult Create()
        {
            StudentViewModel studentView = new StudentViewModel()
            {
                Student = new Students(),
                Courses = new MultiSelectList(db.Courses, "IdCourse", "Name")
            };
            return View(studentView);
        }

        //
        // POST: /Student/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(StudentViewModel students)
        {
            students.Courses = new MultiSelectList(db.Courses, "IdCourse", "Name");
            if (ModelState.IsValid)
            {
                List<Courses> courses = new List<Courses>();
                foreach (var id in students.selectedCourses)
                {
                    courses.Add(db.Courses.Find(Int32.Parse(id)));
                }
                students.Student.Courses = courses;
                db.Students.Add(students.Student);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            students.Courses = new MultiSelectList(db.Courses, "IdCourse", "Name");
            return View(students);
        }

        //
        // GET: /Student/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Students students = db.Students.Find(id);
            if (students == null)
            {
                return HttpNotFound();
            }
            return View(students);
        }

        //
        // POST: /Student/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Students students)
        {
            if (ModelState.IsValid)
            {
                db.Entry(students).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(students);
        }

        //
        // GET: /Student/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Students students = db.Students.Find(id);
            if (students == null)
            {
                return HttpNotFound();
            }
            return View(students);
        }

        //
        // POST: /Student/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Students students = db.Students.Find(id);
            foreach (var course in students.Courses.ToList())
            {
                students.Courses.Remove(course);
            }
            db.Students.Remove(students);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

ColoursOfDance/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -Colour of Dance</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/CSS/simple-sidebar.css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/CSS/navbar.css")
    @Styles.Render("~/Content/themes/base/css")
    @Styles.Render("~/Content/CSS/Home.css")
    @Scripts.Render("~/Scripts/jquery-ui-1.11.1.js")


</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="navbar-brand">
                    <a href=@Url.Action("Index","Home")>
                        <img src="~/Content/Images/logo.png" />
                    </a>
                </div>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><button class="btn btn-primary" onclick="location.href='@Url.Action("About", "Home" )'">Despre</button></li>
                    <li><button class="btn btn-success" onclick="location.href='@Url.Action("Display", "Category" )'">Cursuri</button></li>
                    <li><button class="btn btn-info" onclick="location.href='@Url.Action("Upcoming", "Event" )'">Evenimente</button></li>
                    <li><button class="btn btn-warning" onclick="location.href='@Url.Action("Create","Student")'">Inscrie-te</button></li>
                    <li><button class="btn btn-danger" onclick="location.href='@Url.Action("Contact", "Home" )'">Contact</button></li>

                    <li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            if (User.Identity.Name.Equals("Simi"))
                            {
                                <li><button class="btn btn-primary" onclick="location.href='@Url.Action("Meniu", "Home" )'">Meniu</button></li>
                            }
                        }

                        </li>
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
        <br />
        <div class="container body-content">
            
                @RenderBody()
            @*
                <footer class="container body-content">
                    <p>&copy; @DateTime.Now.Year - Colours of Dance</p>
                </footer>

            *@
            <hr />
        </div>

        @Scripts.Render("~/bundles/bootstrap")
        @Scripts.Render("~/Scripts/animations.js")


        @RenderSection("scripts", required: false)
    </body>
</html>